### ISSUE TITLE
Something wrong (not sure)

### ISSUE THREAD

**Issue by 11111000000** [rstacruz/deku-stateful#2]
Here:  https://gist.github.com/c570a5a3d60aa62d7918  gist, containing Tabs implementation with deku-stateful. It is working as is in deku 1.0. On Tabs first show - all works ok, but on second shown in the same place, we have { state } === undefined inside render fn. Looks like here we have same `path` (0.0.1.0.0.0.0), and it is destroyed onRemove inside stateful decorator.

**Comment by rstacruz** [comment]
i'll have a look, but try jsfiddle next time :)

**Comment by rstacruz** [comment]
1) it looks like you're using the `classnames` syntax for classes.

``` javascript
<div class={['tabs-heading', {'tabs-heading-active': activeTab === i}]}
```

You'll need to use [classnames](https://www.npmjs.com/package/classnames).

``` javascript
import c from 'classnames'
<div class={ c(['tabs-heading', {'tabs-heading-active': activeTab === i}]) }
```

**Comment by rstacruz** [comment]
2) you'll need to hook a `dispatch` function to `deku.createApp`.

**Comment by rstacruz** [comment]
Here's a working example using your code: https://jsfiddle.net/rstacruz/jwLncxfd/

**Comment by rstacruz** [comment]
oh, and deku-stateful requires deku v2.0.0. it's not needed in deku v1, which already has states built-in.

**Comment by 11111000000** [comment]
Of course we are talking about deku 2.0
This code works in 1.0 without problems
appCreate already used in Root-component
Thanks for pointing to classnames, but there is something other issue: Tabs works ok, but then, when its parent component rerender without Tabs and then render with Tabs again, it's `state == undefined` inside `render`.
I apologize for my English, but the problem really is, and it is expressed in the fact that Tabs will not render second time in component like:

```
const ScreenComponent = screens[context.screen.current] || NotFoundScreen

    return (
      <ScreenComponent />
    )
```

deku-stateful not used in that component . I try `deku-stateful` to port my Tabs from 1.0, but without luck and can't understand, why.

**Comment by rstacruz** [comment]
Ahh... i can use some help debugging that one, i can't reproduce it.

Can you try adding a key to that element?

``` html
<TabComponent key='tabs' />
```

**Comment by 11111000000** [comment]
Thanks, I found whats wrong, and fix it here (https://github.com/rstacruz/deku-stateful/pull/3)  .
 when you clean up with `state[model.path] = undefined`, 
`states.hasOwnProperty(model.path)` returns `true`, so you need to use `delete state[model.path]`
