### ISSUE TITLE
pass state to onRemove lifecycle event as well

### ISSUE THREAD

**Issue by borisirota** [rstacruz/deku-stateful#7]
Hi, in my use case I'm using `deku-stateful` to store local state for modal component. I'm attaching `keydown` and `click` events to the document on creation (support closing the modal on `esc` and when clicking outside) and storing the listeners inside the state in order to remove them when the component is being removed.

Currently, I'm not able to use `deku-stateful` because its not giving me the option to clean up this kind of resources on remove.

Thanks !

**Comment by rstacruz** [comment]
Released as v1.6.0.
